[project]
name = "repl-nix-pdfcompilator"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pillow>=11.0.0",
    "pypdf2>=3.0.1",
    "pyqt5>=5.15.11",
]
